### ISSUE TITLE
Support system archive input format

### ISSUE THREAD

**Issue by jmaletic** [srcML/stereocode#22]
Need to support the input format that Nick is working on.   This will be a typical way to run the tool.

One (larage) srcML archive of all the files in a system.   Each file is a unit.   In the case of C++ there will be hpp, cpp pairs.

Get rid of current file list input format - this new format will replace it.

Add option, maybe --system-archive ?

**Comment by nweber28** [comment]
OrderBy supports entire system archive. Input format was removed.
