### ISSUE TITLE
Free function are not distinguished from methods currently

### ISSUE THREAD

**Issue by jmaletic** [srcML/stereocode#23]
Currently, free functions are viewed as methods and stereotyped with the same rules.

Should be identifying free functions and adjusting rules accordingly.

**Comment by nweber28** [comment]
Check code to see if it's easy to determine difference between free function and method.
If function, add stereotype = "free".

**Comment by aalramadan** [comment]
Support added to distinguish free functions from methods.
Free functions are stored separately and not labeled yet.
