### ISSUE TITLE
Add support for single hpp units

### ISSUE THREAD

**Issue by nweber28** [srcML/stereocode#25]
Seg Fault when hpp has no corresponding cpp unit

**Comment by jmaletic** [comment]
Most likely in stereocode.cpp.   The main read look starts on 104.   Maybe the logic in the ifelse starting at 132 is wrong?   

Error maybe on line 108.   secondUnit could be NULL - this is not checked, hence the next line will most likely segfault if it is NULL.

Does it crash on the first occurance  of a single hpp?   Or the last couple ones in the archive?

**Comment by nweber28** [comment]
It crashes on first occurrence of single hpp. 
When the hpp is the first in the list it throws std::logic_error
Otherwise it throws Seg fault

**Comment by nweber28** [comment]
issue with usesAttributeObj() that is used in collaborator() in ClassInfo.cpp (only for single hpp files)
-if statement is triggered that frees a variable from memory and causes subsequent seg faults/logic errors
-will investigate further

**Comment by nweber28** [comment]
Single hpp units now supported. Changes have been pushed to develop branch. Changes have been tested and confirmed to be working for single hpp units.
