### ISSUE TITLE
Multiple classes per file

### ISSUE THREAD

**Issue by aalramadan** [srcML/stereocode#26]
Currently, the tool is capable of processing a file that contains multiple classes, but it assigns the same stereotype to all of them.

Ideally, it should be assigning the correct stereotype to each class.

**Comment by nweber28** [comment]
Going to try to do this without altering ClassInfo.cpp/hpp.

1. Determine if file has mult classes 
2. Process one class at a time (classModel for each class)
3. Output all class stereotypes at once in output report

**Comment by nweber28** [comment]
Need to seperate classes within file into seperate containers.

e.g. Class1, Class2, Class3, etc.

Then send off to evaluate in ClassInfo.cpp

**Comment by aalramadan** [comment]
Support for multiple classes is added now.
Tool is able to process entire archives with multiple classes.
