### ISSUE TITLE
Duplicate stereotypes

### ISSUE THREAD

**Issue by aalramadan** [srcML/stereocode#27]
Sometimes there's a duplicate stereotype.

For "function4" in "example2" archive, this was generated:
command collaborator collaborator wrapper

**Comment by mlcollard** [comment]
Check that this wasn't:

command-collaborator
collaborator
wrapper

**Comment by aalramadan** [comment]
After rechecking, the issue remains in both the main and develop branches.

**Comment by mlcollard** [comment]
What is the duplicate?

commandCollaborator() -> "command collaborator" 
command() -> "command"

Is the duplicate that a "command collaborator" and a "command" should not exist simultaneously? Then ok.

If the duplicate is the two "command"s, then there is no duplicate.

BTW, "command collaborator" should probably be "command-collaborator", as in "non-void-command". But verify this first.

**Comment by aalramadan** [comment]
After checking, the following:
command collaborator, property collaborator, predicate collaborator, and void-accessor collaborator 

should probably be:
command-collaborator, property-collaborator, predicate-collaborator, and void-accessor-collaborator

As you mentioned.

**Comment by aalramadan** [comment]
Removed all collaborator subtypes. Namely:
command **collaborator**, property **collaborator**, predicate **collaborator**, void-accessor **collaborator**, and command **collaborator**.

Rules are disjoint now.
