### ISSUE TITLE
Incidental stereotype is missing

### ISSUE THREAD

**Issue by aalramadan** [srcML/stereocode#28]
Currently, the tool doesn't consider the incidental stereotype.

**Comment by aalramadan** [comment]
It appears that the stereotype "incidental" has been renamed to "stateless" and "stateless" has been renamed as "wrapper" for a more accurate representation of their functionality.

**Comment by mlcollard** [comment]
This only sounds partly right. Do you have sources for this? The papers? Or perhaps commit annotations?

**Comment by aalramadan** [comment]
I was examining Zane's thesis. He mentions:

"The degenerate category is one where the unimplemented methods belong. This category includes empty, stateless (formerly named pure stateless), and wrapper (renamed from stateless)."

Is pure stateless same as incidental?

The comments for the method classModel::stateless() say that the "stateless" stereotype doesn't have any real calls, which matches with the papers say about the "incidental" stereotype. The comments also say that the "wrapper" performs 1 real call, which matches with what the papers say about "stateless".

**Comment by mlcollard** [comment]
Sounding more familiar

**Comment by aalramadan** [comment]
I can confirm that the incidental (also known as pure stateless) was renamed to stateless, and the old stateless was renamed to wrapper. Some unused leftover code related to incidental was removed.
