### ISSUE TITLE
Add warning for XML files that do not contain C++

### ISSUE THREAD

**Issue by nweber28** [srcML/stereocode#31]
Tool should ensure that inputted xml only contains C++ as the tool does not currently support other languages.

**Comment by aalramadan** [comment]
Language check was added. The tool now will warn and quit whenever the input is not C++.

**Comment by mlcollard** [comment]
Why does this quit? Why prevent somebody running in on Java? Or C#?

Given them the warning, but don't quit.

**Comment by aalramadan** [comment]
The tool doesn't support Java or C# yet, quitting allows the user to enter a new input. 

We could also warn them and ask for a new input instead of quitting? or are you talking about an archive with mixed languages?

**Comment by mlcollard** [comment]
You have to let people run it on other languages, just to see what it comes up with. This is a developer tool. As long as it warns about the results, that is fine. Just issue the warning, and don't quit the program.

In any case, do not ask for another input. Command-line tools do not work that way.

**Comment by aalramadan** [comment]
Perfect.
Thank you.

I am thinking about issuing a single warning whenever the tool encounters a unit in a different language. Something like this perhaps?
 
"Warning: one or more input units are not in C++ format and may cause incorrect annotations or program failure."

**Comment by mlcollard** [comment]
"Warning: stereocode is only designed for C++"

**Comment by aalramadan** [comment]
Thanks,

I have made the changes.

The tool now only warns whenever it encounters a unit/input in a different language and continues operation.
