### ISSUE TITLE
No indication of output file for typical case

### ISSUE THREAD

**Issue by mlcollard** [srcML/stereocode#33]
The following (reasonable) command appears to do nothing:

```console
./stereotype example.xml
```

I do see a file, example.xml.annotated.xml appear, but the command does not tell me that.

When the output is the default file, there should be a message from the command indicating the name of the output file.

**Comment by aalramadan** [comment]
I have added a message for the default file. For example, if the input file is called example.xml, the message will be:
*Output file stored in: example.stereotypes.xml*

For the other two options, that is, overwrite and selecting a custom filename, no message is shown.
