### ISSUE TITLE
Default output filename

### ISSUE THREAD

**Issue by mlcollard** [srcML/stereocode#34]
For the following:

```console
./stereotype example.xml
```

The default output file is *example.xml.annotated.xml*.

Leave out the first xml file extension. The filename should be *example.annotated.xml*.

Also, the term "annotated" is long and not very descriptive. Perhaps *stereotypes* as in *example.stereotypes.xml*

**Comment by aalramadan** [comment]
I have changed the filename for the output. It is now **example.stereotypes.xml** as suggested.
