### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by jmaletic** [srcML/stereocode#8]
Need support for different programming languages.

Primitives, stereotype rules, etc.

**Comment by jmaletic** [comment]
Part of this is done.  Basic stuff in place and merged into main.

**Comment by jmaletic** [comment]
All the analysis functionality works on methoModel now.  

Need primitives for other languages.   Some checking on creation.

**Comment by jmaletic** [comment]
primitiveTypes now supports multi language.

Fixed problem with longint vs long int in primitives.   Now much simpler to specify base/primitive types.

**Comment by aalramadan** [comment]
Support for C# and Java is added.

**Comment by jmaletic** [comment]
Closed.
